using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DbCommon.Attributes;
using TihieZoriDb;

namespace TihieZoriDb
{
    public partial class CTableUser
    {
        [StartValue]
        public static List<object> StartFill(CDatabaseTihieZori db)
        {
            var ret = new List<object>
            {
                new User{ UserRole =RoleEnum.Admin,Login = "admin@tihiezori.tk",Email="admin@tihiezori.tk",Password="870CAD28E197E4B7C8C5271408E7022C",salt = "3C0790D9E2DDFE20D940F8109D6070DE"},
                new User{ LandNumber="1",Fio="Ситников Андрей Геннадьевич"},
                new User{ LandNumber="2",Fio="Мочалов Олег Юрьевич"},
                new User{ LandNumber="3",Fio="Ким АлексейАлександрович"},
                new User{ LandNumber="4",Fio="Пяткова Валентина Алексеевна"},
                new User{ LandNumber="5",Fio="Михайленко Виталий Валерьевич"},
                new User{ LandNumber="6",Fio="Глистин Михаил Владимирович"},
                new User{ LandNumber="7",Fio="Пичушкина Виктория Викторовна"},
                new User{ LandNumber="8",Fio="Манин Владимир Юрьевич"},
                new User{ LandNumber="9",Fio="Сидорова Татьяна  Петровна"},
                new User{ LandNumber="10",Fio="Даровых Татьяна Ивановна"},
                new User{ LandNumber="11",Fio="Хромов Александр Сергеевич"},
                new User{ LandNumber="12",Fio="Алпеев Дмитрий Олегович"},
                new User{ LandNumber="13",Fio="Андрес Галина Николаевна"},
                new User{ LandNumber="14",Fio="Кузьмичева Марина Владимировна"},
                new User{ LandNumber="15",Fio="Постовалова Лидия Сергеевна"},
                new User{ LandNumber="16",Fio="Хабарова Людмила Николаевна"},
                new User{ LandNumber="17",Fio="Хомяков Вячеслав Юрьевич"},
                new User{ LandNumber="18",Fio="Репяхов Алексей Викторович"},
                new User{ LandNumber="19",Fio="Жаркова Галина Петровна"},
                new User{ LandNumber="20",Fio="Кузьменко Светлана Викторовна"},
                new User{ LandNumber="21",Fio="Ястребова Галина Юрьевна"},
                new User{ LandNumber="22",Fio="Ледовских Надежда Романовна"},
                new User{ LandNumber="23",Fio="Фомина Оксана Анатольевна"},
                new User{ LandNumber="24",Fio="Андросенко Юрий Александрович"},
                new User{ LandNumber="25",Fio="Гурба Юрий  Юрьевич"},
                new User{ LandNumber="26",Fio="Кудрявцев Игорь Александрович"},
                new User{ LandNumber="27",Fio="Авдиенко Светлана Николаевна"},
                new User{ LandNumber="28",Fio=""},
                new User{ LandNumber="29",Fio=""},
                new User{ LandNumber="30",Fio="Аверина Оксана Юрьевна"},
                new User{ LandNumber="31",Fio="Михалев Дмитрий Владимирович"},
                new User{ LandNumber="32",Fio="Палладина Нина Николаевна"},
                new User{ LandNumber="33",Fio="Кисьова Людмила Кирилловна"},
                new User{ LandNumber="34",Fio="Пиунова Любовь Сергеевна"},
                new User{ LandNumber="35",Fio="Зверев Александр Сергеевич"},
                new User{ LandNumber="36",Fio="Аверина Оксана Юрьевна"},
                new User{ LandNumber="37",Fio="Колесников Анатолий Иванович"},
                new User{ LandNumber="38",Fio="Новиков Евгений Михайлович"},
                new User{ LandNumber="39",Fio="Спрыгин  Дмитрий Вадимович"},
                new User{ LandNumber="40",Fio="Мухин Константин Викторович"},
                new User{ LandNumber="41",Fio=""},
                new User{ LandNumber="42",Fio="Назаров Руслан Геннадьевич"},
                new User{ LandNumber="43",Fio="Захарова Наталья Викторовна"},
                new User{ LandNumber="44",Fio="Ломакин Радион Леонидович"},
                new User{ LandNumber="45",Fio="Косоруков Анатолий Юрьевич"},
                new User{ LandNumber="46",Fio="Чернокозов Артем Юрьевич"},
                new User{ LandNumber="47",Fio="Поллер Андрей Борисович"},
                new User{ LandNumber="48",Fio="Степаненко Александр Александрович"},
                new User{ LandNumber="49",Fio="Гордиенко Дмитрий Анатольевич"},
                new User{ LandNumber="50",Fio="Изыгашева Нина Ефимовна"},
                new User{ LandNumber="51",Fio="Каткова Мария Юрьевна"},
                new User{ LandNumber="52",Fio=""},
                new User{ LandNumber="53",Fio=""},
                new User{ LandNumber="54",Fio=""},
                new User{ LandNumber="55",Fio="Притыка Игорь Николаевич"},
                new User{ LandNumber="56",Fio="Азарова Марина Валерьевна"},
                new User{ LandNumber="57",Fio="Знаменщикова Ульяна Юрьевна"},
                new User{ LandNumber="58",Fio=""},
                new User{ LandNumber="59",Fio="Самсонов Анатолий Иванович"},
                new User{ LandNumber="60",Fio="Кеда Виталий Евгеньевич"},
                new User{ LandNumber="61",Fio="Никулов Борис Михайлович"},
                new User{ LandNumber="62",Fio="Филипьева Тамара Алексеевна"},
                new User{ LandNumber="63",Fio="Жильцова Елена Николаевна"},
                new User{ LandNumber="64",Fio="Чирнега Олег Васильевич"},
                new User{ LandNumber="65",Fio="Тихомирова Юлия Алексеевна"},
                new User{ LandNumber="66",Fio=""},
                new User{ LandNumber="67",Fio=""},
                new User{ LandNumber="68",Fio="Бутылкин Александр Анатольевич"},
                new User{ LandNumber="69",Fio="Башкирова Наталья Владимировна"},
                new User{ LandNumber="70",Fio="Савин Петр  Васильевич"},
                new User{ LandNumber="71",Fio="Степанова Наталья Павлова"},
                new User{ LandNumber="72",Fio="Дударев Андрей Николаевич"},
                new User{ LandNumber="73",Fio="Дударев Николай Николаевич"},
                new User{ LandNumber="74",Fio="Глухих Дмитрий  Игоревич"},
                new User{ LandNumber="75",Fio="Демин Роман  Алексеевич"},
                new User{ LandNumber="76",Fio="Майорова Ирина Владимировна"},
                new User{ LandNumber="77",Fio="Глазачева Оксана Анатольевна"},
                new User{ LandNumber="78",Fio="Урих Татьяна Геннадьевна"},
                new User{ LandNumber="79",Fio="Мигачев Александр Николаевич"},
                new User{ LandNumber="80",Fio="Леонов Анатолий Васильевич"},
                new User{ LandNumber="81",Fio="Юнусова Юлия  Ивановна"},
                new User{ LandNumber="82",Fio="Юнусова Юлия  Ивановна"},
                new User{ LandNumber="83",Fio="Юрьев Алексей Алексеевич"},
                new User{ LandNumber="84",Fio="Алексейцев Александр Алексеевич"},
                new User{ LandNumber="85",Fio="Сорокина Юлия Александровна"},
                new User{ LandNumber="86",Fio="Емельянова Анастасия Владимировна"},
                new User{ LandNumber="87",Fio="Кутькин Антон  Юрьевич"},
                new User{ LandNumber="88",Fio="Кутькина Светлана Гавриловна"},
                new User{ LandNumber="89",Fio="Пархоменко Алексей Александрович"},
                new User{ LandNumber="90",Fio="Белалы Денис  Валерьевич"},
                new User{ LandNumber="91",Fio="Притворов Илья Николаевич"},
                new User{ LandNumber="92",Fio="Чахлова Яна  Ивановна"},
                new User{ LandNumber="93",Fio="Потапкина Елена Анатольевна"},
                new User{ LandNumber="94",Fio="Еременко Елена Владимировна"},
                new User{ LandNumber="95",Fio="Андрющенко Олег Викторович"},
                new User{ LandNumber="96",Fio="Игнатенко Елена Валерьевна"},
                new User{ LandNumber="97",Fio="Игнатенко Сергей Борисович"},
                new User{ LandNumber="98",Fio="Сегин Олег Владимирович"},
                new User{ LandNumber="99",Fio="Артамонова Елена Альбертовна"},
                new User{ LandNumber="100",Fio="Гончарова Лариса Сергеевна"},
                new User{ LandNumber="101",Fio="Суетина Анастасия Николаевна"},
                new User{ LandNumber="102",Fio="Твердун Дмитрий Васильевич"},
                new User{ LandNumber="103",Fio="Малетина Анна Леонидовна"},
                new User{ LandNumber="104",Fio="Филипова Александра Владимировна"},
                new User{ LandNumber="105",Fio="Кошкарев Денис  Юрьевич"},
                new User{ LandNumber="106",Fio=""},
                new User{ LandNumber="107",Fio="Болдырев Владимир Александрович"},
                new User{ LandNumber="108",Fio="Неганова Наталья Александровна"},
                new User{ LandNumber="109",Fio="Иванкова Надежда Валерьевна"},
                new User{ LandNumber="110",Fio="Назарцев Александр Михайлович"},
                new User{ LandNumber="111",Fio="Пикалова Екатерина Сергеевна"},
                new User{ LandNumber="112",Fio=""},
                new User{ LandNumber="113",Fio=""},
                new User{ LandNumber="114",Fio="Фофонов Алексей Михайлович"},
                new User{ LandNumber="115",Fio="Серикова Елена Викторовна"},
                new User{ LandNumber="116",Fio=""},
                new User{ LandNumber="117",Fio=""},
                new User{ LandNumber="118",Fio=""},
            };
            return ret;
        }
    }
}
